/**
 * Paperclip Executor — replaces mock scheduler when Paperclip sidecar is running.
 *
 * Translates between Team Foundry's event-sourced model and Paperclip's
 * company/agent/issue REST API. Polls Paperclip's activity feed and
 * appends equivalent RunEvents to our event store.
 */

import { nanoid } from "nanoid";

import {
  appendEvent,
  getWorkspaceRecord,
  listWorkspaceEvents,
  setWorkspaceStatus,
} from "@/lib/db/client";
import { projectWorkspaceState } from "@/lib/runtime/projector";
import {
  createCompany,
  createAgent,
  createIssue,
  createGoal,
  setSecret,
  pollActivity,
  type PaperclipActivity,
  type PaperclipMapping,
} from "@/lib/runtime/adapters/paperclip";
import type { ArtifactRecord, TaskCard, WorkspaceSnapshot } from "@/lib/types";

// ─── Active executions ───

const activePollers = new Map<string, ReturnType<typeof setInterval>>();
const mappings = new Map<string, PaperclipMapping>();
const budgets = new Map<string, { inputTokens: number; outputTokens: number; estimatedCost: number }>();

// ─── Provider key mapping ───

const PROVIDER_KEY_MAP: Record<string, string> = {
  openai: "OPENAI_API_KEY",
  anthropic: "ANTHROPIC_API_KEY",
  gemini: "GEMINI_API_KEY",
};

function getProviderApiKey(providerId: string): string | undefined {
  const envVar = PROVIDER_KEY_MAP[providerId];
  return envVar ? process.env[envVar] : undefined;
}

// ─── Artifact builder ───

function buildArtifactFromOutput(
  task: TaskCard,
  content: string,
  existingArtifact?: ArtifactRecord,
): ArtifactRecord {
  const artifactId = task.linkedArtifactIds[0] ?? task.id;
  const title = artifactId
    .replace(/-output$/, "")
    .replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());

  if (existingArtifact) {
    const newVersion = existingArtifact.currentVersion + 1;
    return {
      ...existingArtifact,
      currentVersion: newVersion,
      status: "needs_review",
      versions: [
        ...existingArtifact.versions,
        {
          version: newVersion,
          createdAt: Date.now(),
          content,
          notes: "Generated by Paperclip agent.",
          sourceTaskIds: [task.id],
          citations: [],
        },
      ],
    };
  }

  return {
    id: artifactId,
    title,
    type: artifactId,
    status: "draft",
    schema: "markdown-v1",
    provenance: [task.id],
    currentVersion: 1,
    versions: [
      {
        version: 1,
        createdAt: Date.now(),
        content,
        notes: "Generated by Paperclip agent.",
        sourceTaskIds: [task.id],
        citations: [],
      },
    ],
  };
}

// ─── Core executor ───

export async function executePaperclipWorkspace(workspaceId: string): Promise<void> {
  if (activePollers.has(workspaceId)) return;

  const workspace = await getWorkspaceRecord(workspaceId);
  if (!workspace) return;

  const events = await listWorkspaceEvents(workspaceId);
  const snapshot = projectWorkspaceState(workspace, events);

  // 1. Create Paperclip company
  const company = await createCompany(
    snapshot.workspace.title,
    snapshot.summary ?? "Team Foundry workspace",
  );

  const mapping: PaperclipMapping = {
    companyId: company.id,
    agentMap: new Map(),
    issueMap: new Map(),
    taskMap: new Map(),
  };

  // 2. Store LLM API key as Paperclip secret
  const apiKey = getProviderApiKey(snapshot.workspace.providerId);
  if (apiKey) {
    const envVar = PROVIDER_KEY_MAP[snapshot.workspace.providerId];
    if (envVar) {
      await setSecret(company.id, envVar, apiKey);
    }
  }

  // 3. Create agents
  for (const agent of snapshot.agents) {
    const pcAgent = await createAgent(company.id, {
      name: agent.displayName,
      role: agent.roleId,
      title: agent.title,
      systemPrompt: agent.systemPrompt,
    });
    mapping.agentMap.set(agent.agentId, pcAgent.id);
  }

  // 4. Create goal
  const goal = await createGoal(company.id, {
    title: snapshot.workspace.title,
    description: snapshot.summary ?? "",
  });
  mapping.goalId = goal.id;

  // 5. Create issues from tasks (respecting dependency DAG)
  // Sort by phase: tasks with no deps first
  const sortedTasks = [...snapshot.tasks].sort((a, b) => {
    return a.dependencies.length - b.dependencies.length;
  });

  for (const task of sortedTasks) {
    const pcDeps = task.dependencies
      .map((depId) => mapping.issueMap.get(depId))
      .filter(Boolean) as string[];

    const pcAssignee = mapping.agentMap.get(task.ownerAgentId);

    const pcIssue = await createIssue(company.id, {
      title: task.title,
      description: `${task.description}\n\nWork type: ${task.workType}\nAcceptance criteria:\n${task.acceptanceCriteria.map((c) => `- ${c}`).join("\n")}`,
      assigneeId: pcAssignee,
      dependencies: pcDeps,
    });

    mapping.issueMap.set(task.id, pcIssue.id);
    mapping.taskMap.set(pcIssue.id, task.id);
  }

  mappings.set(workspaceId, mapping);
  budgets.set(workspaceId, { inputTokens: 0, outputTokens: 0, estimatedCost: 0 });

  // 6. Emit initial events
  await appendEvent(workspaceId, "run.started", { startedBy: "paperclip" });

  const kickoffId = nanoid();
  await appendEvent(workspaceId, "meeting.started", {
    meetingId: kickoffId,
    title: "Kickoff alignment",
    participantAgentIds: snapshot.agents.map((a) => a.agentId),
  });

  // End kickoff after a short delay
  setTimeout(async () => {
    await appendEvent(workspaceId, "meeting.ended", { meetingId: kickoffId });
  }, 2000);

  // 7. Start polling
  const completedTasks = new Set<string>();
  let lastActivityTimestamp: string | undefined;

  const poller = setInterval(async () => {
    try {
      const activities = await pollActivity(mapping.companyId, lastActivityTimestamp);

      for (const activity of activities) {
        lastActivityTimestamp = activity.createdAt;
        await processActivity(workspaceId, snapshot, mapping, activity, completedTasks);
      }

      // Update budget from activities
      for (const activity of activities) {
        if (activity.data?.inputTokens || activity.data?.outputTokens) {
          const budget = budgets.get(workspaceId)!;
          budget.inputTokens += (activity.data.inputTokens as number) ?? 0;
          budget.outputTokens += (activity.data.outputTokens as number) ?? 0;
          budget.estimatedCost = (budget.inputTokens * 0.003 + budget.outputTokens * 0.015) / 1000;
        }
      }

      // Check if all tasks are done
      if (completedTasks.size >= snapshot.tasks.length && snapshot.tasks.length > 0) {
        clearInterval(poller);
        activePollers.delete(workspaceId);
        await finishExecution(workspaceId, snapshot);
      }
    } catch (err) {
      console.error("[paperclip-executor] Poll error:", err);
    }
  }, 2000);

  activePollers.set(workspaceId, poller);
}

// ─── Activity processing ───

async function processActivity(
  workspaceId: string,
  snapshot: WorkspaceSnapshot,
  mapping: PaperclipMapping,
  activity: PaperclipActivity,
  completedTasks: Set<string>,
): Promise<void> {
  const type = activity.type;

  // Issue started → task.started
  if (type === "issue.started" || type === "issue.in_progress") {
    const ourTaskId = activity.entityId ? mapping.taskMap.get(activity.entityId) : undefined;
    if (!ourTaskId) return;

    const task = snapshot.tasks.find((t) => t.id === ourTaskId);
    if (!task) return;

    await appendEvent(workspaceId, "task.started", {
      taskId: ourTaskId,
      agentId: task.ownerAgentId,
      state: task.workType,
    });
  }

  // Issue completed → task.completed + artifact.updated
  if (type === "issue.completed" || type === "issue.done") {
    const ourTaskId = activity.entityId ? mapping.taskMap.get(activity.entityId) : undefined;
    if (!ourTaskId || completedTasks.has(ourTaskId)) return;

    const task = snapshot.tasks.find((t) => t.id === ourTaskId);
    if (!task) return;

    // Extract content from Paperclip output
    const content = (activity.data?.output as string)
      ?? (activity.data?.result as string)
      ?? `# ${task.title}\n\nCompleted by Paperclip agent.`;

    const existingArtifact = snapshot.artifacts.find(
      (a) => a.id === task.linkedArtifactIds[0],
    );

    await appendEvent(workspaceId, "artifact.updated", {
      artifact: buildArtifactFromOutput(task, content, existingArtifact),
    });

    await appendEvent(workspaceId, "task.completed", {
      taskId: ourTaskId,
      agentId: task.ownerAgentId,
    });

    completedTasks.add(ourTaskId);
  }

  // Agent output (intermediate) → artifact.updated
  if (type === "agent.output" || type === "agent.artifact") {
    const content = (activity.data?.content as string) ?? (activity.data?.output as string);
    if (!content) return;

    // Try to find which task this agent is working on
    const pcAgentId = activity.agentId;
    if (!pcAgentId) return;

    // Find our agent by reverse-mapping
    let ourAgentId: string | undefined;
    for (const [ours, theirs] of mapping.agentMap) {
      if (theirs === pcAgentId) { ourAgentId = ours; break; }
    }
    if (!ourAgentId) return;

    const task = snapshot.tasks.find((t) => t.ownerAgentId === ourAgentId);
    if (!task) return;

    const existingArtifact = snapshot.artifacts.find(
      (a) => a.id === task.linkedArtifactIds[0],
    );

    await appendEvent(workspaceId, "artifact.updated", {
      artifact: buildArtifactFromOutput(task, content, existingArtifact),
    });
  }
}

// ─── Finish sequence ───

async function finishExecution(
  workspaceId: string,
  snapshot: WorkspaceSnapshot,
): Promise<void> {
  // Review meeting
  const reviewId = nanoid();
  await appendEvent(workspaceId, "meeting.started", {
    meetingId: reviewId,
    title: "Review sync",
    participantAgentIds: snapshot.agents.map((a) => a.agentId),
  });

  // Short delay then end meeting + request approval
  setTimeout(async () => {
    await appendEvent(workspaceId, "meeting.ended", { meetingId: reviewId });

    await appendEvent(workspaceId, "approval.requested", {
      gateType: "final_deliverables",
      message: "Review and approve the deliverables before marking the run complete.",
    });

    await setWorkspaceStatus(workspaceId, "awaiting_final_approval");
  }, 2000);
}

// ─── Cleanup ───

export function clearPaperclipSchedule(workspaceId: string): void {
  const poller = activePollers.get(workspaceId);
  if (poller) {
    clearInterval(poller);
    activePollers.delete(workspaceId);
  }
  mappings.delete(workspaceId);
}

// ─── Budget ───

export function getPaperclipBudget(workspaceId: string) {
  return budgets.get(workspaceId) ?? { inputTokens: 0, outputTokens: 0, estimatedCost: 0 };
}
