import type {
  ProviderAdapter,
  ProviderCompletionInput,
  ProviderCompletionResult,
} from "@/lib/types";

function makeMockResult(
  input: ProviderCompletionInput,
  model = "mock-team-foundry-v1",
): ProviderCompletionResult {
  const bullets = input.prompt
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .slice(0, 4)
    .map((line) => `- ${line.replace(/^[-*]\s*/, "")}`)
    .join("\n");

  return {
    model,
    text: bullets || "- Structured response generated by mock provider.",
  };
}

async function fetchJson<T>(url: string, init: RequestInit) {
  const response = await fetch(url, init);

  if (!response.ok) {
    throw new Error(`${response.status} ${response.statusText}`);
  }

  return (await response.json()) as T;
}

function remoteProvider(
  id: string,
  label: string,
  keyEnv: string,
  complete: (
    input: ProviderCompletionInput,
  ) => Promise<ProviderCompletionResult>,
): ProviderAdapter {
  return {
    id,
    label,
    isConfigured: () => Boolean(process.env[keyEnv]),
    complete,
  };
}

export const mockProvider: ProviderAdapter = {
  id: "mock",
  label: "Mock Local Planner",
  defaultModel: "mock-team-foundry-v1",
  isConfigured: () => true,
  complete: async (input) => makeMockResult(input),
};

export const openAiProvider = remoteProvider(
  "openai",
  "OpenAI",
  "OPENAI_API_KEY",
  async (input) => {
    const data = await fetchJson<{
      output?: Array<{ content?: Array<{ text?: string }> }>;
      model?: string;
      usage?: { input_tokens?: number; output_tokens?: number };
    }>("https://api.openai.com/v1/responses", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: process.env.OPENAI_MODEL ?? "gpt-4.1-mini",
        input: [
          { role: "system", content: input.system },
          { role: "user", content: input.prompt },
        ],
      }),
    });

    return {
      model: data.model ?? "openai",
      text:
        data.output?.flatMap((item) => item.content ?? []).map((item) => item.text ?? "").join("\n").trim() ||
        makeMockResult(input).text,
      usage: {
        inputTokens: data.usage?.input_tokens,
        outputTokens: data.usage?.output_tokens,
      },
    };
  },
);

export const anthropicProvider = remoteProvider(
  "anthropic",
  "Anthropic",
  "ANTHROPIC_API_KEY",
  async (input) => {
    const data = await fetchJson<{
      model?: string;
      content?: Array<{ text?: string }>;
      usage?: { input_tokens?: number; output_tokens?: number };
    }>("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": process.env.ANTHROPIC_API_KEY ?? "",
        "anthropic-version": "2023-06-01",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: process.env.ANTHROPIC_MODEL ?? "claude-sonnet-4-6",
        max_tokens: 4096,
        system: input.system,
        messages: [{ role: "user", content: input.prompt }],
      }),
    });

    return {
      model: data.model ?? "anthropic",
      text: data.content?.map((part) => part.text ?? "").join("\n").trim() || makeMockResult(input).text,
      usage: {
        inputTokens: data.usage?.input_tokens,
        outputTokens: data.usage?.output_tokens,
      },
    };
  },
);

export const geminiProvider = remoteProvider(
  "gemini",
  "Gemini",
  "GEMINI_API_KEY",
  async (input) => {
    const model = process.env.GEMINI_MODEL ?? "gemini-2.5-flash";
    const data = await fetchJson<{
      candidates?: Array<{
        content?: { parts?: Array<{ text?: string }> };
      }>;
    }>(
      `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${process.env.GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          systemInstruction: {
            parts: [{ text: input.system }],
          },
          contents: [{ parts: [{ text: input.prompt }] }],
          generationConfig: {
            maxOutputTokens: 4096,
            temperature: 0.7,
          },
        }),
      },
    );

    return {
      model,
      text:
        data.candidates
          ?.flatMap((candidate) => candidate.content?.parts ?? [])
          .map((part) => part.text ?? "")
          .join("\n")
          .trim() || makeMockResult(input).text,
    };
  },
);

export const ollamaProvider: ProviderAdapter = {
  id: "ollama",
  label: "Ollama",
  defaultModel: process.env.OLLAMA_MODEL ?? "llama3.1",
  isConfigured: () => Boolean(process.env.OLLAMA_BASE_URL ?? "http://127.0.0.1:11434"),
  complete: async (input) => {
    const baseUrl = process.env.OLLAMA_BASE_URL ?? "http://127.0.0.1:11434";
    const model = process.env.OLLAMA_MODEL ?? "llama3.1";

    const data = await fetchJson<{ response?: string }>(`${baseUrl}/api/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model,
        prompt: `${input.system}\n\n${input.prompt}`,
        stream: false,
      }),
    });

    return {
      model,
      text: data.response?.trim() || makeMockResult(input, model).text,
    };
  },
};

export const providerRegistry: ProviderAdapter[] = [
  mockProvider,
  geminiProvider,
  anthropicProvider,
  openAiProvider,
  ollamaProvider,
];

export function getProviderAdapter(providerId: string) {
  return (
    providerRegistry.find((provider) => provider.id === providerId) ?? mockProvider
  );
}
